controller_manager:
  ros__parameters:
    # Controllers available
    use_sim_time: true
    update_rate: 50  # Hz integer

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    rb1_base_controller:
      type: diff_drive_controller/DiffDriveController

rb1_base_controller:
  ros__parameters:
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    
    publish_rate: 100.0 # Hz double

    left_wheel_names: ["robot_left_wheel_joint"]
    right_wheel_names: ["robot_right_wheel_joint"]
    
    wheel_separation: 0.436 # meters
    wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.076 # meters

    odom_frame_id: odom
    base_frame_id: robot_base_link
    
    position_feedback: true
    use_stamped_vel: false
    cmd_vel_timeout: 1000.0

    linear.x.has_velocity_limits: false
    linear.x.has_acceleration_limits: false
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.75
    linear.x.min_velocity: -1.75
    linear.x.max_acceleration: 3.0
    linear.x.min_acceleration: -3.0
    linear.x.max_jerk: 0.01
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: false
    angular.z.has_acceleration_limits: false
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 6.0
    angular.z.min_velocity: 0.0
    angular.z.max_acceleration: 6.0
    angular.z.min_acceleration: 0.0
    angular.z.max_jerk: 0.01
    angular.z.min_jerk: 0.0
