controller_manager:
  ros__parameters:
    # Controllers available
    use_sim_time: true
    update_rate: 10  # Hz
    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"
    
    rb1_base_controller:
    
      type: "diff_drive_controller/DiffDriveController"

rb1_base_controller:
  ros__parameters:
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

    base_frame_id: robot_base_link
    left_wheel_names: ["robot_left_wheel_joint"]
    right_wheel_names: ["robot_right_wheel_joint"]
    use_stamped_vel: false

